### ISSUE TITLE
Invincibility Bug

### ISSUE THREAD

**Issue by mcoccia** [lmucs/Coliseo#19]
If you hold down blocking and spam attack you get into a state where you cannot be harmed but can still attack. Makes the game quite easy.

**Comment by ajohn104** [comment]
...I can see why this is a problem, and I know the/a solution, but the solution involves connecting the actual blocking boolean with animation events, and animations are about to be overhauled/added so I'll just fix it with that set of updates. For now we can be OP.

**Comment by ajohn104** [comment]
...actually, I'll do it now so I don't forget.
