### ISSUE TITLE
Change the name of our repository (and everything else)

### ISSUE THREAD

**Issue by alexschneider** [lmucs/Coliseo#5]
What did we decide on again?

**Comment by mcoccia** [comment]
I decided on Coliseum (Colosseum is the specific one in Rome). I think keeping it in english is fine but Amphitheatrum Flavium is the original name of the Colosseum according to the dictionary in my computer and that sounds fancy.

**Comment by rtoal** [comment]
Or, in your case, Ampitheatrum Occulus Virtuum is also too fancy.

**Comment by mcoccia** [comment]
I like the idea of throwing oculus into the name but thats soooo fancy. I like short sweet and easy to say lol.

**Comment by rtoal** [comment]
Coloculoseum? Oculuseum?

**Comment by mcoccia** [comment]
Coliseum Rift: Sight of the Oculus.

**Comment by rtoal** [comment]
Are you going with Coliseum Rift?

**Comment by mcoccia** [comment]
I like that actually. Coliseum Rift.

**Comment by mcoccia** [comment]
We could make everything like time rifty. Roman Coliseum but with time glitches/portals going off. There could be time flashes of roman crowds cheering and that can be how we spawn our enemies. Randomly have time portals open that they jump out of. It would be how we explain the lightsaber + medieval + whatever else we want to throw in. I'll bring it up in our next meeting but I'm excited about it.

**Comment by gastyrd** [comment]
I think that is actually pretty smart, I believe it to be easy enough for us to get some portal animations and it makes sense. Its a good way to tie together the name and game functionality, my vote goes towards that.

**Comment by rtoal** [comment]
The double meaning of "rift" (1. Oculus, 2. timespace discontinuities) here might be too good to pass up. Next class should be devoted to some story creation. Might want to get some of your screenwriter friends to create the settings, mood, game play, engagement, transitions, and all that fun stuff. No shame in soliciting help from friends in the animation department. Or Prof. Schmidt. (Not that you guys are not capable on your own, but expand the team to get more good stuff, you know.)

**Comment by gastyrd** [comment]
Great idea, I say tomorrow we through in a few ideas, cook them a little bit, and once we fill solid about a few, I will pitch them to Prof Schmidt + some anim people to get feedback. How does that sound crew?

**Comment by mcoccia** [comment]
:+1:

**Comment by mcoccia** [comment]
I know we got the repo going. Anything else that needs fixing or is this a closed issue?

**Comment by akrs** [comment]
Not just yet. Once the combat-creation branch gets merged in, we should be good to close.

**Comment by ajohn104** [comment]
I'm honestly intending on finishing the combat-creation (and then opening the combat-perfection) branch a day or two after today (b.c of the midterm). I'm gonna just skip making blocks actually stop attacks in place (and various other animations), and leave it for the follow-up branch. So I'm gonna complete the merge, clean up a ton of code and various unnecessary files, then open a pull-request. The next branch will be the one that takes combat to a genuinely enjoyable (and 95% complete) state. Ideally, that is.

**Comment by ajohn104** [comment]
So, can we close this issue yet? Pretty sure it has all been updated for some time now.

**Comment by ajohn104** [comment]
I really want to close some of these issues.

**Comment by mcoccia** [comment]
I would say we can. If someone wants they can reopen but it should be good.
